services:
  - type: web
    name: remotehub-bot
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: FIREBASE_URL
        sync: false
      - key: INFRA_SERVICES_JSON
        sync: false
      - key: RENDER_API_KEY
        sync: false
      - key: VERCEL_TOKEN
        sync: false
      - key: GOOGLE_TOKEN_JSON
        sync: false
